# Save the output of this file and use podman play kube to import it.
# Created with podman-5.4.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-02-19T20:08:32Z"
  labels:
    app: replica_set
  name: replica_set
spec:
  containers:
  - name: master
    image: mongo:latest
    args:
    - mongod
    - --replSet
    - "rs0"
    - --bind_ip_all
    - --port
    - "27017"
    ports:
    - containerPort: 27017
      hostPort: 27017

  - name: slave01
    image: mongo:latest
    args:
    - mongod
    - --replSet
    - "rs0"
    - --bind_ip_all
    - --port
    - "27018"
    ports: 
    - containerPort: 27018
      hostPort: 27018

  - name: slave02
    image: mongo:latest
    args:
    - mongod
    - --replSet
    - "rs0"
    - --bind_ip_all
    - --port
    - "27019"
    ports: 
    - containerPort: 27019
      hostPort: 27019